/**
 * Message Types for TUIX
 *
 * Defines system-level and component message types for the MVU pattern
 */

import type { KeyEvent, MouseEvent, WindowSize } from './schemas'

// =============================================================================
// System Messages
// =============================================================================

/**
 * System-level messages that all components may receive.
 * These are generated by the framework itself.
 */
export type SystemMsg =
  | { readonly _tag: 'KeyPress'; readonly key: KeyEvent }
  | { readonly _tag: 'MouseEvent'; readonly mouse: MouseEvent }
  | { readonly _tag: 'WindowResize'; readonly size: WindowSize }
  | { readonly _tag: 'Quit' }
  | { readonly _tag: 'Interrupt' }
  | { readonly _tag: 'Suspend' }
  | { readonly _tag: 'Focus'; readonly componentId?: string }
  | { readonly _tag: 'Blur'; readonly componentId?: string }

/**
 * Component messages extend system messages with component-specific messages.
 * Use discriminated unions for type-safe message handling.
 */
export type ComponentMsg<T = never> = SystemMsg | T
